PATH:
  drive:
    image_path: '/content/drive/MyDrive/property_classf_data'
    csv_1_path: '/content/drive/MyDrive/corrected_data.csv'
    csv_2_path: ''
  pwd:
    root_path: '/content'
    org_img_path: ''
    org_img_combined_path: '/content/all_images/'
    new_img_path: ''
    combined_img_path: '/content/images/'
    aug_img_path: ''
