PATH:
  drive:
    image_path: '/content/drive/MyDrive/property_classf_data'
    csv_1_path: '/content/drive/MyDrive/corrected_data.csv'
    csv_2_path: '/content/drive/MyDrive/Classification_activity_2.csv'
    new_img_pth: '/content/drive/MyDrive/property_classf_data/additional_data_for_feb_month/png_clipped'
  pwd:
    root_path: '/content'
    org_img_path: ''
    org_img_combined_path: '/content/all_images/'
    new_img_path: '/content/png_clipped/'
    combined_img_path: '/content/images/'
    aug_img_path: '/content/train_aug/'

train:
  train_py_pth: '/content/pytorch-image-models/train.py'
  train_dir: '/content/train_aug'
  model_type: 'tf_efficientnet_b0'
  batch_size: 8
  img_size: 512
  val_split: 0.2
  epochs: 1
  num_classes: 3

test:
  test_py_pth: '/content/pytorch-image-models/val.py'
  test_dir: '/content/test'
  model_type: 'tf_efficientnet_b0'
  saved_model_path: '/content/model_best.pth.tar'
  batch_size: 1
  img_size: 512
  num_classes: 3
  log_freq: 1

