PATH:
  input: '/home/Columba/PADAM/sample/INPUT'
  intermediate: '/home/Columba/PADAM/sample/INTERMEDIATE'
  output: '/home/Columba/PADAM/sample/OUTPUT'


GENERAL:
  classes: {'Commercial': 1, 'HoA': 2, 'Residential': 3}
  num_processes: 4

